In [1]:
import pandas as pd
from pathlib import Path
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sleep_data=Path("archive/Sleep_health_and_lifestyle_dataset.csv")
sleep_data_df=pd.read_csv(sleep_data)
sleep_data_df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [6]:
disorder_df=sleep_data_df[["Gender", "Age", "Sleep Disorder", "Sleep Duration"]]
disorder_df

     Gender  Age Sleep Disorder  Sleep Duration
0      Male   27           None             6.1
1      Male   28           None             6.2
2      Male   28           None             6.2
3      Male   28    Sleep Apnea             5.9
4      Male   28    Sleep Apnea             5.9
..      ...  ...            ...             ...
369  Female   59    Sleep Apnea             8.1
370  Female   59    Sleep Apnea             8.0
371  Female   59    Sleep Apnea             8.1
372  Female   59    Sleep Apnea             8.1
373  Female   59    Sleep Apnea             8.1

[374 rows x 4 columns]

In [11]:
dub_disorder_df=disorder_df.loc[sleep_df["Gender", "Sleep Duration"]=="Female"]
dub_disorder_df

NameError: name 'sleep_df' is not defined